CREATE TABLE users(
    id INT PRIMARY KEY IDENTITY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(500) NOT NULL,
    enabled TINYINT NOT NULL
);

CREATE TABLE authorities (
    id INT PRIMARY KEY IDENTITY,
    username VARCHAR(50) not null,
    authority VARCHAR(50) not null
);

INSERT INTO users VALUES('admin', '12345',1);
INSERT INTO authorities VALUES('admin', 'write')

--https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/jdbc.html
--CREATE TABLE USERS (
--    USERNAME NVARCHAR2(128) PRIMARY KEY,
--    PASSWORD NVARCHAR2(128) NOT NULL,
--    ENABLED CHAR(1) CHECK (ENABLED IN ('Y','N') ) NOT NULL
--);


--CREATE TABLE AUTHORITIES (
--    USERNAME NVARCHAR2(128) NOT NULL,
--    AUTHORITY NVARCHAR2(128) NOT NULL
--);
--ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHORITY);
-- ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ENABLE;